services:
  vaultwarden:
    image: vaultwarden/server:1.30.5
    restart: unless-stopped
    volumes:
      - ./data/vaultwarden:/data
    environment:
      SIGNUPS_ALLOWED: true
      SIGNUPS_DOMAINS_WHITELIST: example.com
      # Additional environment variables can be set to verify signups
      # SIGNUPS_VERIFY: true
      # SMTP_HOST: ""
      # SMTP_FROM: ""
      # SMTP_PORT: ""
      # SMTP_SECURITY: ""
      # SMTP_USERNAME: ""
      # SMTP_PASSWORD: ""
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`vaultwarden.local`)
      traefik.http.routers.vaultwarden.entrypoints: web
      traefik.http.routers.vaultwarden.middlewares: https-redirect@file
      traefik.http.routers.vaultwarden-secure.rule: Host(`vaultwarden.local`)
      traefik.http.routers.vaultwarden-secure.entrypoints: websecure
      traefik.http.routers.vaultwarden-secure.tls: true

networks:
  default:
    name: common
    external: true