services:
  traefik:
    image: traefik:v3.0.1
    restart: unless-stopped
    command: >-
      --api.dashboard=true
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --providers.file.directory=/etc/traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount the dynamic configuration file to add middlewares and routers etc.
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Mount the Docker socket to allow traefik to listen to events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`traefik.local`)
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.entrypoints: web

# This network can be used to expose services
networks:
  default:
    name: common